### ISSUE TITLE
OSC Formatting for TouchDesigner

### ISSUE THREAD

**Issue by tonyschuite** [hku-ect/NatNet2OSCbridge#14]
Can we have  a Touchdesigner Toggle so the data is named properly in TouchDesigner?

the OSC In CHOP recognises the data properly, however is not naming it in a readable fashion.

**Comment by ikbenmacje** [comment]
I am going to look into that. good excuse to figure out how OSC in Touchdesigner works

**Comment by tonyschuite** [comment]
this can be closed. the outcome is that channels should be parsed in TD.
