### ISSUE TITLE
NatNet2OSCbridge give MOCAP values back in meters instead of millimetres after restart

### ISSUE THREAD

**Issue by ikbenmacje** [hku-ect/NatNet2OSCbridge#24]
Normal behaviour, depending on Motive settings, is that you get the values form Motive in millimetres. Sometimes after a restart of the NatNet2OSCbridge you wil suddenly get the data in meters.

Only fix so far is to restart the bridge a couple of times until the units are again normal.

**Comment by tonyschuite** [comment]
bug appears when:

reconnecting to natnet
adding or removing objects in motive (forcing bridge restart?)
