### ISSUE TITLE
catch exceptions and  handle them

### ISSUE THREAD

**Issue by sphaero** [hku-ect/NatNet2OSCbridge#30]
Instead of ending the application!

For example wrong interface name on Windows

**Comment by ikbenmacje** [comment]
Which exceptions can we think of?
- Wrong interface name
- Wrong interface port
- Invalid Framerate (< 0 or > 60)

**Comment by sphaero** [comment]
we'll find them on our way

**Comment by ikbenmacje** [comment]
Fixed in #33
