### ISSUE TITLE
Mismatched names & data when removing objects

### ISSUE THREAD

**Issue by aaronvark** [hku-ect/NatNet2OSCbridge#5]
When removing an object in Motive, the names & data of objects sent through the bridge will run out of sync, especially when adding new items in the future.

The cause of this is that names were only added to the NatNet specification in 2.9, and the ofxNatNet implementation of this is very hacky. It is disconnected from the rest of the structure.

We've tried catching the problem as it happens and correcting for it, but it can happen consecutively, which makes it impossible to patch in that way.

What we need to do is fix the problem in the core of ofxNatNet.

**Comment by ikbenmacje** [comment]
In my observation if you remove a Rigidbody in Motive then the bridge will keep sending the Rigidbody data over OSC with the last known coordinates. Furthermore if you re add the deleted object with a different name the bridge will sent you the name and data of the old object.

**Comment by sphaero** [comment]
this should be fixed in ofxNatNet: https://github.com/hku-ect/ofxNatNet/pull/4
