### ISSUE TITLE
[Criticial] V3 - No support for Unity Skeleton streaming

### ISSUE THREAD

**Issue by JuriaanGregor** [hku-ect/NatNet2OSCbridge#67]
**Currently in the v3 of the Bridge the hierachy of the bones is not correctly send with the OSC package to Unity, causing multiple cast errors since the data is nil.**

(Missing "full skeleton" option in V3)

**Comment by aaronvark** [comment]
Confirmed. Adding a dropdown button for skeleton mode to the clients should solve this problem.
