### ISSUE TITLE
[BUG] No text drawing in input fields in OSX Sierra

### ISSUE THREAD

**Issue by tonyschuite** [hku-ect/NatNet2OSCbridge#7]
The bridge works in OSX Sierra, however there are no visual aids when it comes to the input fields.

added a screenshot
<img width="1099" alt="screen shot 2017-09-29 at 11 16 11" src="https://user-images.githubusercontent.com/1898121/31009425-ae1a8882-a507-11e7-9649-9641b1c5a040.png">

it does connect
<img width="1094" alt="screen shot 2017-09-29 at 11 17 49" src="https://user-images.githubusercontent.com/1898121/31009471-e38a3e0e-a507-11e7-9a7d-88e9875f24b6.png">

**Comment by tonyschuite** [comment]
Fixed by rebuilding on Sierra 10.12.6

**Comment by ikbenmacje** [comment]
This issue reappeared with the last build 9e119fd 
It might have something to do with a gate keeper issue or font issue
see also: https://github.com/braitsch/ofxDatGui/issues/120
Workaround is to open directly form terminal.
