### ISSUE TITLE
[BUG] No Natnet Data after connecting to natnet server on Sierra

### ISSUE THREAD

**Issue by tonyschuite** [hku-ect/NatNet2OSCbridge#9]
I get the debug error "[error] ofxNatNet: initialize failed"

connection to natnet server works, but no data

**Comment by aaronvark** [comment]
This is an issue in the ofxNatNet addon. The fix is as follows:

Replace instances of "NatNetVersion" with "ServerVersion" in ofxNatNet.cpp, in functions "Unpack()" and "unpackRigidbodies()"

**Comment by tonyschuite** [comment]
fix worked...

here is the OSX Sierra 10.12.6 Build
[NatNet2OSCBridgeDebug.zip](https://github.com/hku-ect/NatNet2OSCbridge/files/1356098/NatNet2OSCBridgeDebug.zip)
